# -*-makefile-*-
# Spheral++ Infrastructure package makefile
#-------------------------------------------------------------------------------
PKGNAME = Infrastructure
PKGDIR = $(PKGNAME)/
LIBTARGET = libSpheral_$(PKGNAME).$(DYLIBEXT)
SRCTARGETS = \
	SpheralError.cc
# PYFFLETARGETS =

LINKLIST = linklist
# PYFFLELIST = pyfflelist
SPHERALTOP = ..
ARCH = $(SPHERALARCH)

#EXTRAFLAGS = -DDEBUG

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master
