# -*-makefile-*-
# Spheral++ MHD BPL wrap package makefile
#-------------------------------------------------------------------------------
PKGNAME = FVMHD
PKGDIR = $(PKGNAME)/
MODTARGET = $(PKGNAME).$(SHLIBEXT)
PYSTETARGETS = \
	ConductingFluidNodeList.pyste \
	FVMHD.pyste 

LINKLIST = linklist
SPHERALTOP = ../..

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master

