# -*-makefile-*-
# Spheral++ pybindgen CXXTypes package makefile
#-------------------------------------------------------------------------------
PKGNAME = CXXTypes
PKGDIR = $(PKGNAME)/
PBGMODTARGET = $(PKGNAME).$(DYLIBEXT)
PBGTARGETS = \
	CXXTypes.C

SPHERALTOP = ../..

#EXTRAFLAGS = -DDEBUG

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master
