compilers:
- compiler:
    spec: clang@9.0.0
    paths:
      cc: /usr/tce/packages/clang/clang-9.0.0/bin/clang
      cxx: /usr/tce/packages/clang/clang-9.0.0/bin/clang++
      f77: /usr/tce/packages/gcc/gcc-8.1.0/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-8.1.0/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.1.0
    paths:
      cc: /usr/tce/packages/gcc/gcc-8.1.0/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.1.0/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.1.0/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-8.1.0/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.3.1
    paths:
      cc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
