# -*-makefile-*-
# Spheral++ CXXTests BPL wrap package makefile
#-------------------------------------------------------------------------------
PKGNAME = CXXTests
PKGDIR = $(PKGNAME)/
MODTARGET = $(PKGNAME).$(SHLIBEXT)
PYSTETARGETS = \
	testNodeIterators.pyste \
	testFieldListIndexing.pyste \
	testNewtonRaphson.pyste

SPHERALTOP = ../..

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master
