compilers::
- compiler:
      spec: rocmcc@=6.2.0
      paths:
        cc:  /usr/tce/packages/rocmcc/rocmcc-6.2.0-magic/bin/amdclang
        cxx: /usr/tce/packages/rocmcc/rocmcc-6.2.0-magic/bin/amdclang++
        f77: /usr/tce/packages/rocmcc/rocmcc-6.2.0-magic/bin/amdflang
        fc:  /usr/tce/packages/rocmcc/rocmcc-6.2.0-magic/bin/amdflang
      flags: {}
      operating_system: rhel8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
