packages::
  all:
    # This defaults us to machine specific flags of ivybridge which allows
    # us to run on broadwell as well
    target: [zen2]
    compiler: [gcc, cce, clang]
    providers:
      mpi: [cray-mpich]
  cmake:
    version: [3.24.2, 3.23.1, 3.22.4, 3.21.1, 3.19.2, 3.14.5]
    buildable: false
    externals:
    - spec: cmake@3.14.5
      prefix: /usr/tce/packages/cmake/cmake-3.14.5
    - spec: cmake@3.19.2
      prefix: /usr/tce/packages/cmake/cmake-3.19.2
    - spec: cmake@3.21.1
      prefix: /usr/tce/packages/cmake/cmake-3.21.1
    - spec: cmake@3.22.4
      prefix: /usr/tce/packages/cmake/cmake-3.22.4
    - spec: cmake@3.23.1
      prefix: /usr/tce/packages/cmake/cmake-3.23.1
    - spec: cmake@3.24.2
      prefix: /usr/tce/packages/cmake/cmake-3.24.2
  cuda:
    version: [11.4.120]
    buildable: false
    externals:
    - spec: cuda@11.4.120
      prefix: /opt/toss/cudatoolkit/11.4/
  hip:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: hip@5.2.3
      prefix: /opt/rocm-5.2.3/hip
    - spec: hip@5.3.0
      prefix: /opt/rocm-5.3.0/hip
    - spec: hip@5.4.1
      prefix: /opt/rocm-5.4.1/hip
    - spec: hip@5.4.3
      prefix: /opt/rocm-5.4.3/hip
    - spec: hip@5.5.1
      prefix: /opt/rocm-5.5.1/hip
    - spec: hip@5.6.1
      prefix: /opt/rocm-5.6.1/hip
    - spec: hip@5.7.0
      prefix: /opt/rocm-5.7.0/hip
    - spec: hip@5.7.1
      prefix: /opt/rocm-5.7.1/hip
    - spec: hip@6.1.1
      prefix: /opt/rocm-6.1.1/hip
    - spec: hip@6.2.0
      prefix: /opt/rocm-6.2.0/hip
  llvm-amdgpu:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: llvm-amdgpu@5.2.3
      prefix: /opt/rocm-5.2.3/llvm
    - spec: llvm-amdgpu@5.3.0
      prefix: /opt/rocm-5.3.0/llvm
    - spec: llvm-amdgpu@5.4.1
      prefix: /opt/rocm-5.4.1/llvm
    - spec: llvm-amdgpu@5.4.3
      prefix: /opt/rocm-5.4.3/llvm
    - spec: llvm-amdgpu@5.5.1
      prefix: /opt/rocm-5.5.1/llvm
    - spec: llvm-amdgpu@5.6.1
      prefix: /opt/rocm-5.6.1/llvm
    - spec: llvm-amdgpu@5.7.0
      prefix: /opt/rocm-5.7.0/llvm
    - spec: llvm-amdgpu@5.7.1
      prefix: /opt/rocm-5.7.1/llvm
    - spec: llvm-amdgpu@6.1.1
      prefix: /opt/rocm-6.1.1/llvm
    - spec: llvm-amdgpu@6.2.0
      prefix: /opt/rocm-6.2.0/llvm
  hsa-rocr-dev:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: hsa-rocr-dev@5.2.3
      prefix: /opt/rocm-5.2.3/
    - spec: hsa-rocr-dev@5.3.0
      prefix: /opt/rocm-5.3.0/
    - spec: hsa-rocr-dev@5.4.1
      prefix: /opt/rocm-5.4.1/
    - spec: hsa-rocr-dev@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: hsa-rocr-dev@5.5.1
      prefix: /opt/rocm-5.5.1/
    - spec: hsa-rocr-dev@5.6.1
      prefix: /opt/rocm-5.6.1/
    - spec: hsa-rocr-dev@5.7.0
      prefix: /opt/rocm-5.7.0/
    - spec: hsa-rocr-dev@5.7.1
      prefix: /opt/rocm-5.7.1/
    - spec: hsa-rocr-dev@6.1.1
      prefix: /opt/rocm-6.1.1/
    - spec: hsa-rocr-dev@6.2.0
      prefix: /opt/rocm-6.2.0/
  rocminfo:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: rocminfo@5.2.3
      prefix: /opt/rocm-5.2.3/
    - spec: rocminfo@5.3.0
      prefix: /opt/rocm-5.3.0/
    - spec: rocminfo@5.4.1
      prefix: /opt/rocm-5.4.1/
    - spec: rocminfo@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: rocminfo@5.5.1
      prefix: /opt/rocm-5.5.1/
    - spec: rocminfo@5.6.1
      prefix: /opt/rocm-5.6.1/
    - spec: rocminfo@5.7.0
      prefix: /opt/rocm-5.7.0/
    - spec: rocminfo@5.7.1
      prefix: /opt/rocm-5.7.1/
    - spec: rocminfo@6.1.1
      prefix: /opt/rocm-6.1.1/
    - spec: rocminfo@6.2.0
      prefix: /opt/rocm-6.2.0/
  rocm-device-libs:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: rocm-device-libs@5.2.3
      prefix: /opt/rocm-5.2.3/
    - spec: rocm-device-libs@5.3.0
      prefix: /opt/rocm-5.3.0/
    - spec: rocm-device-libs@5.4.1
      prefix: /opt/rocm-5.4.1/
    - spec: rocm-device-libs@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: rocm-device-libs@5.5.1
      prefix: /opt/rocm-5.5.1/
    - spec: rocm-device-libs@5.6.1
      prefix: /opt/rocm-5.6.1/
    - spec: rocm-device-libs@5.7.0
      prefix: /opt/rocm-5.7.0/
    - spec: rocm-device-libs@5.7.1
      prefix: /opt/rocm-5.7.1/
    - spec: rocm-device-libs@6.1.1
      prefix: /opt/rocm-6.1.1/
    - spec: rocm-device-libs@6.2.0
      prefix: /opt/rocm-6.2.0/
  rocprim:
    version: [5.2.3, 5.3.0, 5.4.1, 5.4.3, 5.5.1, 5.6.1, 5.7.0, 5.7.1, 6.1.1, 6.2.0]
    buildable: false
    externals:
    - spec: rocprim@5.2.3
      prefix: /opt/rocm-5.2.3/
    - spec: rocprim@5.3.0
      prefix: /opt/rocm-5.3.0/
    - spec: rocprim@5.4.1
      prefix: /opt/rocm-5.4.1/
    - spec: rocprim@5.4.3
      prefix: /opt/rocm-5.4.3/
    - spec: rocprim@5.5.1
      prefix: /opt/rocm-5.5.1/
    - spec: rocprim@5.6.1
      prefix: /opt/rocm-5.6.1/
    - spec: rocprim@5.7.0
      prefix: /opt/rocm-5.7.0/
    - spec: rocprim@5.7.1
      prefix: /opt/rocm-5.7.1/
    - spec: rocprim@6.1.1
      prefix: /opt/rocm-6.1.1/
    - spec: rocprim@6.2.0
      prefix: /opt/rocm-6.2.0/
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.28%cce@15.0.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-cce-15.0.1-magic
    - spec: cray-mpich@8.1.28%cce@16.0.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-cce-16.0.1-magic
    - spec: cray-mpich@8.1.28%cce@17.0.0
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-cce-17.0.0-magic
    - spec: cray-mpich@8.1.28%gcc@12.1.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-gcc-12.1.1-magic
    - spec: cray-mpich@8.1.28%rocmcc@5.5.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-rocmcc-5.5.1-magic
    - spec: cray-mpich@8.1.28%rocmcc@5.6.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-rocmcc-5.6.1-magic
    - spec: cray-mpich@8.1.28%rocmcc@5.7.0
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-rocmcc-5.7.0-magic
    - spec: cray-mpich@8.1.28%rocmcc@5.7.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.28-rocmcc-5.7.1-magic
    - spec: cray-mpich@8.1.29%rocmcc@6.1.1
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.29-rocmcc-6.1.1-magic
    - spec: cray-mpich@8.1.30%rocmcc@6.2.0
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-8.1.30-rocmcc-6.2.0-magic
  python:
    buildable: false
    version: [3.10.8]
    externals:
    - spec: python@3.10.8
      prefix: /usr/tce/packages/python/python-3.10.8
  elfutils:
    buildable: false
    version: [0.187]
    externals:
    - spec: elfutils@0.187
      prefix: /usr
  libunwind:
    buildable: false
    version: [8.0.1]
    externals:
    - spec: libunwind@8.0.1
      prefix: /usr
  papi:
    buildable: false
    version: [7.0.0.1]
    externals:
    - spec: papi@7.0.0.1
      prefix: /opt/cray/pe/papi/7.0.0.1
