packages:
  all:
    providers:
      blas: [openblas]
      lapack: [openblas]
      mpi: [cray-mpich]
      pkgconfig: [pkg-config]
      zlib-api: [zlib]
  llvm-amdgpu:
    externals:
    - spec: llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocmcc-6.4.3-magic
      extra_attributes:
        compilers:
          c: /usr/tce/packages/rocmcc/rocmcc-6.4.3-magic/bin/amdclang
          cxx: /usr/tce/packages/rocmcc/rocmcc-6.4.3-magic/bin/amdclang++
          fortran: /usr/tce/packages/rocmcc/rocmcc-6.4.3-magic/bin/amdflang
  cmake:
    version: [3.24.2]
    buildable: false
    externals:
    - spec: cmake@3.24.2
      prefix: /usr/tce/packages/cmake/cmake-3.24.2
  gmake:
    version: [4.2.1]
    buildable: false
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  perl:
    version: [5.26.3]
    buildable: false
    externals:
    - spec: perl@5.26.3
      prefix: /usr

  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@9.0.1%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/cray-mpich/cray-mpich-9.0.1-rocmcc-6.4.3-magic

  hip:
    version: [6.4.3]
    buildable: false
    externals:
    - spec: hip@6.4.3%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocmcc-6.4.3-magic/
  hsa-rocr-dev:
    version: [6.4.3]
    buildable: false
    externals:
    - spec: hsa-rocr-dev@6.4.3%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocm-6.4.3-magic/
  rocminfo:
    version: [6.4.3]
    buildable: false
    externals:
    - spec: rocminfo@6.4.3%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocm-6.4.3-magic/
  rocm-device-libs:
    version: [6.4.3]
    buildable: false
    externals:
    - spec: rocm-device-libs@6.4.3%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocm-6.4.3-magic/
  rocprim:
    version: [6.4.3]
    buildable: false
    externals:
    - spec: rocprim@6.4.3%llvm-amdgpu@6.4.3
      prefix: /usr/tce/packages/rocmcc/rocm-6.4.3-magic/

# ------ SYSTEM LIBS -------
  readline:
    externals:
    - spec: readline@7.0
      prefix: /usr
    buildable: false
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
    buildable: false
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
    buildable: false
  pkg-config:
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  tcl:
    externals:
    - spec: tcl@8.6.8
      prefix: /usr
    buildable: false
  tk:
    externals:
    - spec: tk@8.6.8
      prefix: /usr/lib64
    buildable: false
  netlib-lapack:
    buildable: false
    externals:
    - spec: netlib-lapack@3.9.0
      prefix: /usr
  openblas:
    buildable: false
    externals:
    - prefix: /usr
      spec: openblas@0.3.15
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
    buildable: false
  expat:
    externals:
    - spec: expat@2.4.1
      prefix: /usr
    buildable: false
  gdbm:
    externals:
    - spec: gdbm@1.19
      prefix: /usr
    buildable: false
  gettext:
    externals:
    - spec: gettext@0.19
      prefix: /usr
    buildable: false
  libffi:
    externals:
    - spec: libffi@3.3
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.1.1
      prefix: /usr
    buildable: false
  ossp-uuid:
    externals:
    - spec: ossp-uuid@1.62
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
    buildable: false
  ncurses:
    externals:
    - spec: ncurses@6.1.20180224+termlib abi=6
      prefix: /usr/lib64
    buildable: false
  libxml2:
    externals:
    - spec: libxml2@3.4.2
      prefix: /usr/lib64
    buildable: false
  libpciaccess:
    externals:
    - spec: libpciaccess@0.14
      prefix: /usr/lib64
    buildable: false
  tar:
    buildable: false
    externals:
    - spec: tar@1.26
      prefix: /usr
  libbsd:
    externals:
    - spec: libbsd@0.12.2
      prefix: /usr/lib64
    buildable: false
  libmd:
    externals:
    - spec: libmd@1.1.0
      prefix: /usr/lib64
    buildable: false
  libxcrypt:
    externals:
    - spec: libxcrypt@4.1.1
      prefix: /lib64
    buildable: false
  sqlite:
    externals:
    - spec: sqlite@3.36.0
      prefix: /usr
    buildable: false
  hwloc:
    externals:
    - spec: hwloc@2.12.2
      prefix: /usr/lib64/hwloc
    buildable: false
