# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/config.yaml
# -------------------------------------------------------------------------
config:
  install_tree:
    padded_length: 128
    root: $spack/../installs
  misc_cache: $spack/../misc_cache
  test_stage: $spack/../test_stage
  source_cache: $spack/../source_cache
  build_stage: $spack/../build_stage
concretizer:
  unify: false
  reuse: false
  compiler_mixing: false
repos:
  builtin:
    destination: $spack/../packages-1.2.2
    git: "https://github.com/spack/spack-packages.git"
