# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/config.yaml
# -------------------------------------------------------------------------
config:
  install_tree:
    padded_length: 128
  misc_cache: $spack/../misc_cache
  test_stage: $spack/../test_stage
  source_cache: $spack/../source_cache
  build_stage:
    - $spack/../build_stage
repos:
  builtin:
    destination: $spack/../packages
    git: "https://github.com/spack/spack-packages.git"
    commit: a251c075e32d54b77c283538b45e9327e88f02d2
