# -*-makefile-*-
# Spheral++ Utilities/test package makefile
#-------------------------------------------------------------------------------
PKGNAME = UtilitiesTests
PKGDIR = $(PKGNAME)/
LIBTARGET = lib$(PKGNAME).$(DYLIBEXT)
EXETARGETS = \
	testFastMath.exe

LINKLIST = linklist
PYFFLELIST = pyfflelist
SPHERALTOP = ../..
ARCH = $(SPHERALARCH)

#EXTRAFLAGS = 
#EXTRALIBS = $(PAPILIBS) 
#EXTRALIBS = -lgsl -lgslcblas

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_master
