# -*-makefile-*-
# Spheral++ SimulationControl package makefile
#-------------------------------------------------------------------------------
PKGNAME = SimulationControl
PKGDIR = $(PKGNAME)/
PYTHONTARGETS = \
	Spheral.py \
	Spheral1d.py \
	Spheral2d.py \
	Spheral3d.py \
	SpheralPickle.py \
	SpheralTestUtilities.py \
	SpheralTimer.py \
	SpheralConservation.py \
	SpheralController.py \
	SpheralOptionParser.py \
	SpheralVisitDump.py \
	SpheralVoronoiSiloDump.py \
	Spheral1dVizDump.py \
	SpheralGnuPlotUtilities.py \
	findLastRestart.py \
	Pnorm.py \
	numericalIntegration.py \
	newtonRaphson.py \
	NodeHistory.py

LINKLIST = linklist
PYFFLELIST = pyfflelist
SPHERALTOP = ..
ARCH = $(SPHERALARCH)

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master
