compilers:
- compiler:
    spec: clang@9.0.0
    paths:
      cc: /usr/tce/packages/clang/clang-9.0.0/bin/clang
      cxx: /usr/tce/packages/clang/clang-9.0.0/bin/clang++
      f77: /usr/tce/packages/xl/xl-beta-2019.06.20/bin/xlf2003_r
      fc: /usr/tce/packages/xl/xl-beta-2019.06.20/bin/xlf2003_r
    flags: {}
    operating_system: rhel7
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.3.1
    paths:
      cc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
      cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
      f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: ppc64le
    modules: []
    environment: {}
    extra_rpaths: []
