set(LC_TPL_DIR "/usr/gapps/Spheral/tpl/lc_toss3_gcc8.1.0-release-tpl-only/install/tpl" CACHE STRING "")

set(zlib_BUILD OFF CACHE BOOL "Option to build zlib")
set(boost_BUILD OFF CACHE BOOL "Option to build boost")
set(eigen_BUILD OFF CACHE BOOL "Option to build eigen")
set(qhull_BUILD OFF CACHE BOOL "Option to build qhull")
set(polytope_BUILD OFF CACHE BOOL "Option to build polytope")
set(hdf5_BUILD OFF CACHE BOOL "Option to build hdf5")
set(silo_BUILD OFF CACHE BOOL "Option to build silo")
set(opensubdiv_BUILD OFF CACHE BOOL "Option to build Opensubdiv")
set(aneos_BUILD OFF CACHE BOOL "Option to build ANEOS third party lib")
set(conduit_BUILD OFF CACHE BOOL "Option to build Conduit")
set(axom_BUILD OFF CACHE BOOL "Option to build Axom")

set(pybind11_BUILD OFF CACHE BOOL "Option to build pybind11")
set(python_BUILD OFF CACHE BOOL "Option to build python")
set(pip_BUILD OFF CACHE BOOL "Option to build pip")

set(aneos_DIR "${LC_TPL_DIR}/aneos" CACHE STRING "")
set(axom_DIR "${LC_TPL_DIR}/axom" CACHE STRING "")
set(boost_DIR "${LC_TPL_DIR}/boost" CACHE STRING "")
set(conduit_DIR "${LC_TPL_DIR}/conduit" CACHE STRING "")
set(eigen_DIR "${LC_TPL_DIR}/eigen" CACHE STRING "")
set(hdf5_DIR "${LC_TPL_DIR}/hdf5" CACHE STRING "")
set(opensubdiv_DIR "${LC_TPL_DIR}/opensubdiv" CACHE STRING "")
set(polytope_DIR "${LC_TPL_DIR}/polytope" CACHE STRING "")
set(pybind11_DIR "${LC_TPL_DIR}/pybind11" CACHE STRING "")
set(python_DIR "${LC_TPL_DIR}/python" CACHE STRING "")
set(qhull_DIR "${LC_TPL_DIR}/qhull" CACHE STRING "")
set(silo_DIR "${LC_TPL_DIR}/silo" CACHE STRING "")
set(zlib_DIR "${LC_TPL_DIR}/zlib" CACHE STRING "")
