# Find Python
option(USE_PYTHON "Generate Python interface" ON)
if (USE_PYTHON)
  set(Python_ADDITIONAL_VERSIONS 2.7)
  if (PYTHON_EXE)
    set(PYTHON_EXECUTABLE ${PYTHON_EXE})
    include(FindPythonVersion)
    find_python_version()
    find_package(PythonLibs)
    string(REPLACE "/bin/python${PYTHON_VERSION}" "" PYTHON_ROOT ${PYTHON_EXE})
    set(PYTHON_INCLUDE_DIR "${PYTHON_ROOT}/include/site/python${PYTHON_VERSION}")
    set(PYTHON_INCLUDE_DIRS "${PYTHON_ROOT}/include/python${PYTHON_VERSION}")
    set(PYTHON_LIB_DIR "${PYTHON_ROOT}/lib")
    set(PYTHON_LIBRARY "${PYTHON_LIB_DIR}/libpython.a")
  else()
    find_package(PythonLibs REQUIRED)
    find_package(PythonInterp REQUIRED)
    set(PYTHON_VERSION "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}")
  endif()

  if (PYTHON_EXECUTABLE)
    include(FindPythonModule)
    if(NOT ENABLE_CXXONLY)
      find_python_module(PYB11Generator REQUIRED)
      find_python_module(mpi4py REQUIRED)
      find_python_module(pybind11 REQUIRED)
      find_python_module(matplotlib REQUIRED)
      find_python_module(Gnuplot REQUIRED)
      find_python_module(stl REQUIRED)
    endif()
    set(PY_PYB11 1)
    include_directories("${PYTHON_INCLUDE_DIR}")
    include_directories("${PYTHON_INCLUDE_DIRS}")
    if (PY_PYB11)
      set(HAVE_PYTHON ON)
      message(STATUS "Found Python version ${PYTHON_VERSION}")
      message(STATUS "Using Python executable ${PYTHON_EXECUTABLE}")
    else()
      set(HAVE_PYTHON OFF)
    endif()
  endif()

  if (HAVE_PYTHON)
    include(FindPythonSitePackages)
    find_python_site_packages()
  endif()
else()
  set(HAVE_PYTHON OFF)
endif()

