# -*-makefile-*-
# Spheral++ CXXTests package makefile
#-------------------------------------------------------------------------------
PKGNAME = CXXTests
PKGDIR = $(PKGNAME)/
LIBTARGET = libSpheral_$(PKGNAME).$(DYLIBEXT)
SRCTARGETS = \
	testNodeIteratorsInst.cc
SPHERALTOP = ..
ARCH = $(SPHERALARCH)

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_master
