#!/bin/sh
COMP=clang-ibm
#COMP=vacpp
#COMP=gnu
#export CXXFLAGS="-mcpu=power8 -mtune=power8 -O3 -mcmodel=medium"

../configure LIBS="-lm" --with-compilers=$COMP --with-openmp   --without-scipy  --with-opt=3 
