
message(STATUS "Configuring Spheral version ${SPHERAL_VERSION}")

set(SPHERAL_INSTALL_INCLUDE_DIR "include" CACHE STRING "")
set(SPHERAL_INSTALL_CONFIG_DIR "lib" CACHE STRING "")
set(SPHERAL_INSTALL_LIB_DIR "lib" CACHE STRING "")
set(SPHERAL_INSTALL_BIN_DIR "bin" CACHE STRING "")
set(SPHERAL_INSTALL_CMAKE_MODULE_DIR "${SPHERAL_INSTALL_CONFIG_DIR}/cmake" CACHE STRING "")
set(SPHERAL_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX} CACHE STRING "" FORCE)
set(SPHERAL_INSTALL_SPHERAL "Spheral" CACHE STRING "")

include(CMakePackageConfigHelpers)

configure_package_config_file(
  ${SPHERAL_ROOT_DIR}/cmake/spheral_cxx-config.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/spheral_cxx-config.cmake
  INSTALL_DESTINATION ${SPHERAL_INSTALL_CONFIG_DIR}
  PATH_VARS
  SPHERAL_INSTALL_INCLUDE_DIR
  SPHERAL_INSTALL_LIB_DIR
  SPHERAL_INSTALL_BIN_DIR
  SPHERAL_INSTALL_CMAKE_MODULE_DIR
  SPHERAL_INSTALL_SPHERAL
)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/spheral_cxx-config.cmake
  DESTINATION ${SPHERAL_INSTALL_CMAKE_MODULE_DIR}
)

