#!/usr/bin/env python3

from builtins import str
from builtins import object
import os, string, time, sys
import getopt
import time
import platform
import sys
import optparse, re, copy
import subprocess

d_debug= 0

SYS_TYPE = os.environ.get('SYS_TYPE','')
# This is better than platform.node() some of the time, because it differentiates between jade, jadeita, and jadedev.
LCSCHEDCLUSTER = os.environ.get('LCSCHEDCLUSTER',platform.node())

def cpu_count():
    """Reliably return the number of physical cores.
       multiprocessing.cpu_count() and psutil.cpu_count() do not do this correctly.
       Instead parse the output of 'lscpu'.
    """
    if 'rzwhippet' in platform.node():
        return 56
    elif 'rzgenie' in platform.node() or 'ruby' in platform.node():
        return 36
    else:
        try:
            p = subprocess.run(["lscpu",], stdout=subprocess.PIPE, text=True)
        except Exception as e:
            print ("Error running lscpu to get cpu count\n")
            sys.exit(1)
           
        out = p.stdout
        lines = out.split('\n')

        for line in lines:
            key, value = line.split(":")
            if key == "Core(s) per socket":
                cores_per_socket = int(value)
            if key == "Socket(s)":
                sockets = int(value)
                break

        return (cores_per_socket * sockets)


#---------------------------------------------------------------------------
def createBsubFile(inCommand, inAllOptions):
    inFilename= inAllOptions.msubFilename

    FILE= open(inFilename, "w")

    bsubOutputFilename= inFilename + ".out"

    import platform
    thisNode= platform.node()

    #BSUB -G guests
    #BSUB -o jobRetry.output              # output is sent to file job.output
    #BSUB -J nightlyBlueosBuild           # name of the job
    #BSUB -W 240                          # alloc time - was defaulting to 30 minutes
    FILE.write("#BSUB -G %s \n" % machineSettings.options.group) 
    FILE.write("#BSUB -o " + bsubOutputFilename + "\n")
    FILE.write("#BSUB -J " + inFilename +  "\n")
    FILE.write("#BSUB -W %d \n" % machineSettings.options.allocTime )
    FILE.write("#BSUB -n " + str(machineSettings.options.numProcs) +  "\n")
    FILE.write("\n\n")
    FILE.write("setenv MACHINE_TYPE " + machineSettings.options.machineType + '\n')
    FILE.write("setenv SYS_TYPE " + SYS_TYPE + '\n')

    FILE.write(""+ '\n')
    FILE.write("date"+ '\n')
    FILE.write("cd " + os.getcwd() + "\n")
    FILE.write(inCommand+ '\n')

    FILE.write("date"+ '\n')
    FILE.close()
    return inFilename
    
#---------------------------------------------------------------------------
def createMsubFile(inCommand, inAllOptions):

    inFilename= inAllOptions.msubFilename

    FILE= open(inFilename, "w")

    msubOutputFilename= inFilename + ".out"

    import platform
    thisNode= platform.node()

    FILE.write("#!/bin/tcsh" + '\n')
    FILE.write("\n")
    FILE.write("#MSUB -N " + inFilename + '\n')
    FILE.write("#MSUB -j oe "+ '\n')                       # directs all err output to stdout ")
    FILE.write("#MSUB -o " + msubOutputFilename + '\n')
    FILE.write("#MSUB -l nodes=" +  str(machineSettings.options.numNodes)+ ":ppn=" + str(cpu_count()) + '\n')
    FILE.write("#MSUB -l walltime=%d:00\n" % machineSettings.options.allocTime )
#    FILE.write("#MSUB -V                         # exports all environment var "+ '\n')

    if machineSettings.options.name != 'cray':
        FILE.write("#MSUB -q " +  machineSettings.options.partition + '\n')
        FILE.write("#MSUB -l gres=ignore  "+ '\n')
        FILE.write("#MSUB -A " + machineSettings.options.bank + "                        #bank to use "+ '\n')

    FILE.write(""+ '\n')

    # LLNL specific
    if machineSettings.options.name == 'cray':
        FILE.write("source " + "/usr/projects/kull/developers/tools/kull_cshrc.csh " + '\n')

    # rzmerl and zin specific - increase limits to avoid pthread_create errors.
    if machineSettings.options.name == 'chaos5BatchCapable':
        FILE.write('limit maxproc 7168'+'\n')
        FILE.write('limit descriptors 7168'+'\n')

    FILE.write("setenv MACHINE_TYPE " + machineSettings.options.machineType + '\n')
    FILE.write("setenv SYS_TYPE " + SYS_TYPE + '\n')

    FILE.write(""+ '\n')
    FILE.write("date"+ '\n')
    FILE.write("cd " + os.getcwd() + "\n")
    FILE.write(inCommand+ '\n')

    FILE.write("date"+ '\n')


    FILE.close()
    return inFilename

#---------------------------------------------------------------------------
def createSbatchFile(inCommand, inAllOptions):
    ''' Some clusters don't have msub wrappers so we use sbatch directly.
        Options are still the same as those used for the msub just the submission is different
        so reusing most of the same variables here.
    '''
    inFilename= inAllOptions.msubFilename

    FILE= open(inFilename, "w")

    sbatchOutputFilename= inFilename + ".out"
    sbatchErrorFilename= inFilename + ".error"

    import platform
    thisNode= platform.node()

    FILE.write("#!/bin/tcsh" + '\n')
    FILE.write("\n")
    FILE.write("#SBATCH --job-name=" + inFilename + '\n')
    FILE.write("#SBATCH --error="+ sbatchErrorFilename + '\n')                       # directs all err output to stdout ")
    FILE.write("#SBATCH --output="+ sbatchOutputFilename + '\n')                       # directs all other output to stdout ")
    FILE.write("#SBATCH --nodes=" +  str(machineSettings.options.numNodes)+ "\n")
    FILE.write("#SBATCH --ntasks=" + str(cpu_count()) +"\n") # Is this OKay?  Not sure if we want to default ntasks.
    FILE.write("#SBATCH --time=%d\n" % machineSettings.options.allocTime )

    if machineSettings.options.name != 'cray':
        FILE.write("#SBATCH --partition=" +  machineSettings.options.partition + '\n')
        FILE.write("#SBATCH --account=" + machineSettings.options.bank + "                        #bank to use "+ '\n')

    FILE.write(""+ '\n')

    # LLNL specific
    FILE.write("setenv MACHINE_TYPE " + machineSettings.options.machineType + '\n')
    FILE.write("setenv SYS_TYPE " + SYS_TYPE + '\n')

    FILE.write(""+ '\n')
    FILE.write("date"+ '\n')
    FILE.write("cd " + os.getcwd() + "\n")
    FILE.write(inCommand+ '\n')

    FILE.write("date"+ '\n')


    FILE.close()
    return inFilename

#---------------------------------------------------------------------------
from optparse import SUPPRESS_HELP
class NoErrOptionParser(optparse.OptionParser):
    # Found this online... modified some
    def __init__(self,*args,**kwargs):
        self.valid_args_cre_list = []
        optparse.OptionParser.__init__(self, *args, **kwargs)

    def error(self,msg):
        optparse.OptionParser.error(self,msg)
        pass

    def add_option(self,*args,**kwargs):
        self.valid_args_cre_list.append(re.compile('^'+args[0] +  "[ =]"))
        self.valid_args_cre_list.append(re.compile('^' + args[0] + '$'))
        optparse.OptionParser.add_option(self, *args, **kwargs)

    def parse_args(self,*args,**kwargs):
        # filter out invalid options
        args_to_parse = args[0]
        # all args are stored in args_to_parse
        new_args_to_parse = []
        for a in args_to_parse:
            for cre in self.valid_args_cre_list:
                if cre.match(a):
                    new_args_to_parse.append(a)
                    break
                elif not a.startswith("-"):
                    new_args_to_parse.append(a)
                    break

        #args that'll be used are stored in new_args_to_parse
        # remove old values and insert the new
        while len(args_to_parse) > 0:
            args_to_parse.pop()
        for a in new_args_to_parse:
            args_to_parse.append(a)

        return optparse.OptionParser.parse_args(self,*args,**kwargs)

#------------------------------------------------------------------------
class AttributeDict (dict):
    """A dictionary whose items can be accessed as attributes."""
    def __getattr__(self, name):
        return self[name]
    def __setattr__(self, name, value):
        self[name] = value
    def __repr__(self):
        from io import StringIO
        out = StringIO()
        print("AttributeDict(", file=out)
        keys = list(self.keys())
        keys.sort()
        for key in keys:
            print("  ", key, " = ", repr(self[key]), ",", file=out)
        print(")", file=out)
        s = out.getvalue()
        out.close()
        return s
    __str__ = __repr__
#------------------------------------------------------------------------

class MachineInfo (object):

    def __init__ (self, **options):
        "Must not throw an exception -- object must always get created."
        super(MachineInfo, self).__init__()


        self.options = AttributeDict(
            # Run settings

            name= '',
            allocTime= '',
            machineType= '',
            batch = True,
            numNodes=4,
            numProcs= None,
            group = '',
            partition= 'pbatch',

            atsArgs= [],

        )
        try:
            self.options.update(options)
        except Exception as e:
            self.set(INVALID, 'Bad options: ' + e)
            return


#---------------------------------------------------------------------------
# MAIN
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
# Setup option parser
#---------------------------------------------------------------------------
parser= NoErrOptionParser(add_help_option=False)

(options, args) = parser.parse_args(sys.argv[:])

#---------------------------------------------------------------------------
useCpu= cpu_count()
#---------------------------------------------------------------------------

blueosSettings= MachineInfo(
    name='blueos',
    machineType='blueos_3_ppc64le_ib_p9',
    batch= False,
    allocTime = 240,
    group = "guests",
    partition='pdebug',
    numProcs = 128,
    numNodes=4,
    bank='guests',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=40",
              "--continueFreq=15",
              "--timelimit=120",
              "--glue='noDraco=True'",
              "--glue='noVisit=True'",
              "--glue='noOpacityServer=True'",
              "--glue='noCxxUnitTesting=True'",
            ],
)

rzmantaSettings= MachineInfo(
    name='blueos',
    machineType='rzmanta',
    batch= True,
    allocTime = 240,
    group = "guests",
    partition='pdebug',
    numProcs = 128,
    #numNodes=,
    #bank='science',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=8",
              "--continueFreq=15",
              "--timelimit=480",
              "--glue='noDraco=True'",
              "--glue='noVisit=True'",
              "--glue='noOpacityServer=True'",
              "--glue='noCxxUnitTesting=True'",
            ],
)

bgqSettings= MachineInfo(
    name='bgq',
    machineType='rzuseq',
    batch= False,
    allocTime = 480,

    partition='pdebug',
    numNodes=64,
    bank='science',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=8",
              "--continueFreq=15",
              "--timelimit=480",
              "--glue='noDraco=True'",
              "--glue='noVisit=True'",
              "--glue='noOpacityServer=True'",
              "--glue='noCxxUnitTesting=True'",
            ],

)

chaos5BatchCapable = MachineInfo(
    name='chaos5BatchCapable',
    machineType='SlurmProcessorScheduled',
    batch = True,
    partition='pbatch',
    numNodes=8,
    bank='wbronze',
    allocTime = 180,
    atsArgs=[ "--allInteractive",
              "--glue='independent=True'",
              "--continueFreq=15",
              "--timelimit=60",
              "--npMax=%s" % cpu_count()
            ],

)

chaos5NotBatchCapable= MachineInfo(
    name='chaos5NotBatchCapable',
    machineType='SlurmProcessorScheduled',
    batch=False,
    numNodes=4,
    partition='pdebug',
    bank='wbronze',
    allocTime = 180,
    atsArgs=[ "--allInteractive",
              "--continueFreq=15",
              "--timelimit=60",
              "--glue='independent=True'"
    ],

)

craySettings= MachineInfo(
    name='cray',
    machineType='cray',
    atsArgs=[
              '--allInteractive',
              "--timelimit=60",
              "--glue='independent=True'",
    ],

)

chamaSettings= MachineInfo(
    name='chama',
    machineType='SlurmProcessorScheduled',
    batch = False,
    partition='nw',
    numNodes=8,
    bank='FY140244', # TAG's WC_IC
    wcid='FY140244', # TAG's WC_IC
    allocTime = 240,
    atsArgs=[ "--allInteractive",
              "--glue='independent=True'",
              "--glue='noDraco=True'",
              "--glue='noOverlink=True'",
              "--glue='noOpacityServer=True'",
              "--glue='noTracker=True'",
              "--timelimit=60",
              "--npMax=%s" % cpu_count()
            ],

)

glorySettings= MachineInfo(
    name='glory',
    machineType='SlurmProcessorScheduled',
    batch = False,
    partition='nw',
    numNodes=8,
    bank='FY140244', # TAG's WC_IC
    wcid='FY140244', # TAG's WC_IC
    allocTime = 240,
    atsArgs=[ "--allInteractive",
              "--glue='independent=True'",
              # "--glue='noDraco=True'",
              "--glue='noOverlink=True'",
              "--glue='noOpacityServer=True'",
              "--glue='noTracker=True'",
              "--timelimit=60",
              "--npMax=%s" % cpu_count()
            ],

)

toss3Settings= MachineInfo(
    name='rzgenie',
    machineType='SlurmProcessorScheduled',
    batch= False,
    #allocTime = 240,
    allocTime = 180,
    partition='pdebug',
    #numNodes=4,
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=%s"%(useCpu),
              "--continueFreq=15",
              "--timelimit=120",
            ],

)

toss3Batch= MachineInfo(
    name='rztopaz',
    machineType='SlurmProcessorScheduled',
    batch= True,
    allocTime = 360,
    partition='pbatch',
    numNodes=4,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=36",
              "--continueFreq=15",
              "--timelimit=120",
            ],

)

rztopazSettings= MachineInfo(
    name='rztopaz',
    machineType='SlurmProcessorScheduled',
    batch= False,
    allocTime = 60,
    partition='pdebug',
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=36",
              "--continueFreq=15",
              "--timelimit=60",
            ],
)

toss4Settings= MachineInfo(
    name='toss4machine',
    machineType='slurm36',
    batch= False,
    allocTime = 180,
    partition='pdebug',
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=36",
              "--continueFreq=15",
              "--timelimit 120m",
            ],
)

toss4BatchSettings= MachineInfo(
    name='toss4BatchMachine',
    machineType='slurm36',
    batch= True,
    allocTime = 180,
    partition='pdebug',
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=36",
              "--continueFreq=15",
              "--timelimit 120m",
            ],
)

# Ruby settings (same as TOSS4 interactive without pdebug)
rubySettings= MachineInfo(
    name='toss4machine',
    machineType='slurm36',
    batch= False,
    allocTime = 180,
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=36",
              "--continueFreq=15",
              "--timelimit 120m",
            ],
)

#  settings when rzwhippet is running flux natively
rzwhippetSettings= MachineInfo(
    name='rzwhippet',
    machineType='flux00',
    batch= False,
    allocTime = 180,
    numNodes=2,
    bank='wbronze',
    atsArgs=[
              "--glue='independent=True'",
              '--allInteractive',
              "--npMax=%s"%(useCpu),
              "--continueFreq=15",
              "--timelimit=120",
            ],
)

# Determine machine settings to use
#-----------------------------------------------------------------------
# Determine machine settings to use
# NOTE:
# The options are obtained from argv, the defaults for the options are from the machineSettings
# options are used later to figure what to do....  machine settings are used for non-init options
#
#-----------------------------------------------------------------------

if platform.processor() == 'ppc64':
    machineSettings = bgqSettings

elif 'PRGENVMODULES' in os.environ:   # cray machine
    machineSettings = craySettings

elif 'chama' in SYS_TYPE:
    machineSettings = chamaSettings

elif 'glory' in SYS_TYPE:
    machineSettings = glorySettings

elif 'blue' in SYS_TYPE:
    machineSettings = blueosSettings

elif 'toss_3' in SYS_TYPE:
    if 'rzgenie' in LCSCHEDCLUSTER or 'jadedev' == LCSCHEDCLUSTER or 'zindev' == LCSCHEDCLUSTER:
        # Developer machines are interactive
        machineSettings = toss3Settings
    elif '--partition=pdebug' in sys.argv and not '--batch' in sys.argv:
        # Need short queue settings
        machineSettings = rztopazSettings
    else:
        # Put it in batch.
        machineSettings = toss3Batch
elif 'toss_4' in SYS_TYPE:
    if 'ruby' in  LCSCHEDCLUSTER:
        machineSettings = rubySettings
    else:
        machineSettings = toss4Settings
else:
    print("Could not determine machine settings to use.")
    sys.exit(1)

print("Selected machine settings for: ", machineSettings.options.name)

#----------------------------------------------------------
# inits and defaults
#----------------------------------------------------------
import random
import time
ezatsLocaltime = time.localtime()
ezatsStartTime = time.strftime("%y%m%d%H%M%S",ezatsLocaltime)
msubFilenameDefault= "tmpAts." +  ezatsStartTime + ".job"
bsubFilenameDefault= "tmpAts." +  ezatsStartTime + ".job"


#---------------------------------------------------------------------------
# options affecting machine settings
#---------------------------------------------------------------------------

parser.add_option( "--allocTime", action="store", type="int", metavar="minutes", dest="allocTime",
                   help = "The amount of time for the batch job (in minutes) .")

parser.add_option( "--interactive", action="store_true", dest="interactive",
                   help = "Run ats interactively in SLURM (default is false if batch system detected.)")

parser.add_option( "--machineType", action="store", type="string", metavar="MACHINE_TYPE", dest="machineType",
                   help="Sets the MACHINE_TYPE for ats.")

parser.add_option( "--numNodes", action="store", type="int", metavar="number of nodes", dest="numNodes",
                   help="Number of nodes to allocate for ats to run in.")

parser.add_option( "--partition", action="store", type="string", metavar="scheduler partition", dest="partition",
                   help = "Partition in which to run jobs.")

parser.add_option( "--bank", action="store", type="string", metavar="account to charge",dest="bank",
                   help = "Bank to use for batch job.")

parser.add_option("--wcid", action="store", type="string", metavar="WC-ID to assign", dest='wcid',
                  #default = machineSettings.options.bank,
                  help = "HERT WC-ID to use for batch job.")

parser.add_option( "--threaded", action="store_true", dest="threaded",
                   help = "Run threaded tests. NOTE ATS must run these on login node (no salloc). ")

parser.add_option( "--nogpu", action="store_true", dest="nogpu",
                   help = "For blueos. Filters out gpu test. Used in conjunction with threaded option.")

parser.add_option( "--gpuonly", action="store_true", dest="gpuonly",
                   help = "For blueos nvcc runs.  Filters for gpu tests. Used in conjunction with threaded option.")

parser.add_option( "--sanitize", action="store_true", dest="sanitize",
                   help = "Run sanitize tests. NOTE These need a specific build to work. ")


#---------------------------------------------------------------------------
# other options
#---------------------------------------------------------------------------
parser.add_option( "--msubFilename", action="store", type="string", metavar="msub file name", dest='msubFilename',
                   default = msubFilenameDefault, help = "The name of the generated ats msub job script that will be run.")

parser.add_option( "--bsubFilename", action="store", type="string", metavar="msub file name", dest='bsubFilename',
                   default = bsubFilenameDefault, help = "The name of the generated ats bsub job script that will be run.")

parser.add_option( '--timelimit', dest='timelimit', default=30,
                   help='Set the default time limit on each test. The value may be given as a digit followed by an s, m, or h to give the time in seconds, minutes (the default), or hours.')

# The P2 version is a sym-link to the latest python 2 version of ATS.  There's a P3 when we're ready for Python3
#parser.add_option( "--atsExe", action="store", type="string", dest="atsExe", default="/usr/apps/ats/7.0.P2/bin/ats", help="Sets which ats to use.")
parser.add_option( "--atsExe", action="store", type="string", dest="atsExe", default="/usr/apps/ats/7.0.P3/bin/ats", help="Sets which ats to use.")
#parser.add_option( "--atsExe", action="store", type="string", dest="atsExe", default="/usr/apps/ats/7.0.111/bin/ats", help="Sets which ats to use.")

parser.add_option( "--addOp", action="store", type="string", dest="extraEzatsArgs", default='',
                  help="Adds extra job scheduler option to ezats.")

parser.add_option( "--skip", action='store_true', dest='skip',  default = False,
                   help='skip actual execution of the tests, but show filtering results and missing test files.')

parser.add_option( "--testpath", action="store", type="string", dest="testpath", default="",
                  help="Specifies a path for ezats to use for unique test output.")

parser.add_option( "--debug-build", action="store_true", dest="debugbuild", default=False,
                   help="assume we are testing a debug build and should skip expensive (level>=100) tests.")

(options, args) = parser.parse_args(sys.argv[:])

# If running in SLURM, use defaults of less nodes and pdebug partition
if options.interactive:
    machineSettings.options.batch = False
    machineSettings.options.numNodes = 4

    if "muir" in platform.node():
        machineSettings.options.partition = 'views'
    else:
        machineSettings.options.partition = 'pdebug'

    machineSettings.options.allocTime = 60

if options.allocTime:
    machineSettings.options.allocTime = options.allocTime

if options.machineType:
    machineSettings.options.machineType = options.machineType

if options.numNodes:
    machineSettings.options.numNodes = options.numNodes

if options.partition:
    machineSettings.options.partition = options.partition

if options.bank:
    machineSettings.options.bank = options.bank

if options.wcid:
    machineSettings.options.wcid = options.wcid

if (d_debug==1):
    print("options= ", options)


whichAts= sys.argv[0]
atsArgs = sys.argv[1:]

if "--help" in atsArgs or "-h" in atsArgs or "-help" in atsArgs:
    print("------------------------------------------------------------------")
    print("Options available for only ezats: ")
    print("------------------------------------------------------------------")
    parser.print_help()
    print("------------------------------------------------------------------")
    print("Options for ats: ")
    print("------------------------------------------------------------------")
    from subprocess import check_call
    check_call([options.atsExe, "-h"])

    print("\n\n------------------------------------------------------------------")
    print("ezats sets these ATS options: ")
    print("------------------------------------------------------------------")
    print('\n'.join(machineSettings.options.atsArgs))
    print('\n\n')

    sys.exit(0)

# Convert array of strings to a string with spaces for delimiters
atsArgs = " ".join(str(x) for x in atsArgs)

#---------------------------------------------------------------------------
# Added this section to allow ezats to determine an appropriate filesystem
# to use for testing for this machine.  The filesystem can then be passed
# onto to tests in ats that request a location.
#
# The appropriate filesystem to use for each machine is determined by the
# lustre file system summary and max bandwith tables
# https://computing.llnl.gov/?set=resources&page=lc_lustre
#---------------------------------------------------------------------------

#def checkFileSystem(path, timeout=4):
# 04/25/23: SD: Increasing the timeout as they're having lustre problems and we 
# suspect this is causing failures. Revisit and change back to 4 when lustre issues
# are resolved 
def checkFileSystem(path, timeout=30):

    def timeoutFunction( timeout, timeoutReturn, func, *args):

        res = timeoutReturn

        def handleTimeOut( signum, frame):
            raise TimeOutException

        import signal
        theOldHandler = signal.signal( signal.SIGALRM, handleTimeOut)
        signal.alarm(timeout)
        try:
            try:
                res = func(*args)
            finally:
                signal.signal(signal.SIGALRM, theOldHandler)
        except:
            pass #catch the TimeOutException

        signal.alarm(0)

        return res

    def canWriteToFileSystem(path):

        from tempfile import TemporaryFile
        from os import makedirs
        try:
            if not os.path.exists(path):
                makedirs( path )
            TemporaryFile(dir=path)
        except:
            return False

        return True


    return timeoutFunction( timeout, False, canWriteToFileSystem, path )

#---------------------------------------------------------------------------

#----------------------------------------------------------
# Examine options:
#----------------------------------------------------------

print("Note:  the srun message 'error: ioctl(TIOCGWINSZ)' can be ignored.  \n[It means the process is trying to do something that requires a tty \nbut it's not doing either a read or write.]\n")

#----------------------------------------------------------
# get args to add  - added threaded option to the ezatsArgs or it would be passed to ats
#----------------------------------------------------------
batchArgs= ['partition', 'bank', 'wcid']
ezatsArgs= ['addOp', 'batch', 'interactive', 'name', 'allocTime', 'atsExe', 'machineType', 'bsubFile', 'msubFile', 'bank', 'testpath' , 'threaded', 'gpuonly' ,'nogpu', 'numProcs', 'group', 'sanitize', 'debug-build']

# Add glue arg to pass unique file system test path to ats
toAdd= """ --glue='testpath=str("%s")' """ % options.testpath

# Add threaded arg to filter for threaded or non threaded tests.  Otherwise all versions will run, and threaded will be run incorrectly
if options.threaded:
    if options.nogpu:
        toAdd += """ --filter="'nt' in locals()" --filter="'ngpu' not in locals()" """
    elif options.gpuonly:
        toAdd += """ --filter="'nt' in locals()" --filter="'ngpu' in locals()" """
    # This version only works if we're using os.system - execv call fails because filter is split incorrectly
    else:
        toAdd += """ --filter="'nt' in locals()" """
else:
    toAdd += """ --filter="'nt' not in locals()" """

if options.sanitize:
        toAdd += """ --filter="sanitize==1" """

if options.debugbuild:
    toAdd += """ --filter="level<100" """

for machineArg in machineSettings.options:
    if machineSettings.options[machineArg] == '' or \
       machineSettings.options[machineArg] == None:
        continue
    if machineArg not in atsArgs and \
             machineArg != 'atsArgs' and \
             machineArg not in batchArgs and \
             machineArg not in ezatsArgs:
        toAdd += "--" + machineArg + " " + str(machineSettings.options[machineArg]) + " "
toAdd+= "  "

for machineArg in machineSettings.options.atsArgs:
    theArg= machineArg.replace("=", " ").split()[0]
    if theArg not in atsArgs:
        toAdd += machineArg + " "

atsArgs= options.atsExe + " " +  toAdd + atsArgs
finalCommandToRun= atsArgs
#----------------------------------------------------------
# clean finalCommandToRun
#----------------------------------------------------------
listCommandsToRemove= ['--'+x for x in ezatsArgs]

if machineSettings.options.batch:
    listCommandsToRemove.append('--batchHost')
    listCommandsToRemove.append('--batchT')
    listCommandsToRemove.append('--batchP')
    listCommandsToRemove.append('--batch ')
    listCommandsToRemove.append('--partition')
if machineSettings.options.machineType=='SlurmProcessorScheduled' or machineSettings.options.machineType=='blueos_3_ppc64le_ib_p9':
    listCommandsToRemove.append('--numNodes')
    listCommandsToRemove.append('--wcid')

for machineArg in machineSettings.options.atsArgs:
    if 'REMOVE' in machineArg:
        listCommandsToRemove.append(machineArg)

# Remove all extra spaces
finalCommandToRun = re.sub(r"\s+", " ", finalCommandToRun.strip())

# Remove extra options for both batch and interactive
if len(listCommandsToRemove) > 0:
    for unwantedCommand in listCommandsToRemove[:]:
        startPos= finalCommandToRun.find(unwantedCommand)
        if d_debug:
            print("DEBUG: ", unwantedCommand, "-- found start pos= ", startPos)
        if startPos!= -1:        #if found
            endPos= finalCommandToRun.find(" -", startPos+2)
            if d_debug:
                print("DEBUG: ", "end pos= ", endPos)

            if endPos== -1:
                endPos= finalCommandToRun.find("--", startPos+2)
                if d_debug:
                    print("DEBUG: ", "found end pos= ", endPos)
            if endPos== -1: # looking at last option, backtrack to find the last space..
               endPos= finalCommandToRun.rfind(' ')
               if d_debug:
                   print("DEBUG: ", "rfind() found end pos= ", endPos)

            if endPos < startPos:
               finalCommandToRun= finalCommandToRun[:endPos]
            else:
               finalCommandToRun= finalCommandToRun[:startPos] + finalCommandToRun[endPos:]

            if d_debug:
                print("DEBUG: ", unwantedCommand, "-----> ", finalCommandToRun)

#finalCommandToRun= finalCommandToRun.replace(options.extraEzatsArgs, '', 1)
realFinalCommandToRun= None

#----------------------------------------------------------
# if MSUB, SBATCH or BSUB
#----------------------------------------------------------
if machineSettings.options.batch:
    print("--- ATS COMMAND ---\n", finalCommandToRun)
    if "blueos" in SYS_TYPE:
        bsubFilename= createBsubFile(finalCommandToRun, options)
        batchtype = 'bsub < ' # have to have an input file redirect for bsub
        print("\nWritten to %s batch filename: %s " %(batchtype, bsubFilename))
        cmd = batchtype + ' ' + bsubFilename
    elif 'magma' in LCSCHEDCLUSTER:
        sbatchFilename= createSbatchFile(finalCommandToRun, options)
        batchtype = 'sbatch'
        print("\nWritten to %s batch filename: %s " %(batchtype, sbatchFilename))
        cmd = batchtype + ' ' + sbatchFilename
    elif 'mica' in LCSCHEDCLUSTER:
        sbatchFilename= createSbatchFile(finalCommandToRun, options)
        batchtype = 'sbatch'
        print("\nWritten to %s batch filename: %s " %(batchtype, sbatchFilename))
        cmd = batchtype + ' ' + sbatchFilename
    else:
        msubFilename= createMsubFile(finalCommandToRun, options)
        batchtype = 'msub'
        print("\nWritten to %s batch filename: %s " %(batchtype, msubFilename))
        cmd = batchtype + ' ' + msubFilename

    if not options.skip:
        from subprocess import check_call
        print("Running0: ", cmd)
        #check_call( cmd.split() )
        os.system( cmd )
    else:
        if 'msub' in batchtype:
            print("SKIP option in ats command.  ' msub ",  msubFilename, "' was not executed.")
        elif 'sbatch' in batchtype:
            print("SKIP option in ats command.  ' sbatch ",  sbatchFilename, "' was not executed.")
        else:
            print("SKIP option in ats command.  ' bsub ",  bsubFilename, "' was not executed.")


    sys.exit()

#----------------------------------------------------------
# else SALLOC or threaded w/out salloc
#----------------------------------------------------------
else:

    os.environ["MACHINE_TYPE"] = machineSettings.options.machineType
    if machineSettings.options.name in ['rzwhippet_flux']:
       os.environ["MACHINE_TYPE"] = "flux00"
    os.environ["BATCH_TYPE"] = "None"

    if platform.processor() == 'ppc64':
        numProcsLine = ""
    else:
        numProcsLine = " -n %d" % ( machineSettings.options.numNodes* cpu_count() )

    if machineSettings.options.allocTime:
        if machineSettings.options.name in ['rzwhippet_flux']:
            allocTime = "-t %dm" % machineSettings.options.allocTime
        else:
            allocTime = "--time=%d:00" % machineSettings.options.allocTime
    else:
        allocTime = ""

    HERT_WC_ID = ''
    if machineSettings.options.name in ['chama', 'glory']:
        HERT_WC_ID = ' --account=' + machineSettings.options.wcid

    if machineSettings.options.name in ['rzwhippet_flux']:
        finalCommandToRun= "flux alloc --exclusive "  \
                               + " " + allocTime \
                               + HERT_WC_ID \
                               + options.extraEzatsArgs \
                               + " -N " + str(machineSettings.options.numNodes) \
                               + numProcsLine + " " \
                               + finalCommandToRun
                               # +  " -p " + machineSettings.options.partition  + " " 
    # Threaded tests under ats should NOT use salloc
    elif not options.threaded and 'blue' not in os.environ['SYS_TYPE']:
        finalCommandToRun= "salloc  --exclusive "  \
                               + " " + allocTime \
                               + HERT_WC_ID \
                               + options.extraEzatsArgs \
                               + " -N " + str(machineSettings.options.numNodes) \
                               + numProcsLine \
                               +  " -p " + machineSettings.options.partition  + " " \
                               + finalCommandToRun
    else:
        finalCommandToRun += " --numNodes="+ str(machineSettings.options.numNodes)
    #sys.exit()

if (d_debug==1):
    print("whichAts= ", whichAts)
    print("finalCommandToRun after= ", finalCommandToRun)

#----------------------------------------------------------
# Find filter part and keep whole
#
#  [05/30] The problem is from splitting the command into argsToUse. If we ran w/ something other than os.execv, maybe this will work correctly.
tagFilter= finalCommandToRun.find('--filter')
comboMark= False
for anArg in sys.argv[1:]:
    if '--filter' in anArg and ("'" in anArg):
        comboMark= True
if tagFilter != -1 and comboMark==True:
    startFilter= finalCommandToRun.find("'", tagFilter)
    endFilter= finalCommandToRun.find("'", startFilter+1)
    filterPart= finalCommandToRun[tagFilter:endFilter+1]
    filterPart= filterPart.replace("'", '')
    argsToUse= finalCommandToRun[0:tagFilter].split() + [filterPart] + finalCommandToRun[endFilter+1:].split()
else:
    argsToUse= finalCommandToRun.split()

if realFinalCommandToRun is not None:
    print("Running:\n ", realFinalCommandToRun)
    if (d_debug==1):
        print("Really running:\n ", finalCommandToRun)
else:
    print("Running:\n ", finalCommandToRun)
if (d_debug==1):
    print("atsExe= ", options.atsExe)
    print("atsArgs= ", argsToUse)

#os.system(finalCommandToRun) # [SD] Problem was execv & the way it took the args split up was breaking the filter, and cmd failed.
# Tested on rzgenie (pdebug), rztopaz (pbatch), and bgq (pdebug)
from subprocess import check_call
try:
    check_call( finalCommandToRun,shell=True )
except Exception as e:
    print("Caught - non-zero exit status 3 - thrown by final command", e)
    print("Tests appear to execute correctly...but this output is here to keep an eye on this.")

#  [SD] This was the former call before adding threaded option
#import os
#if not machineSettings.options.batch:
#   os.execv("/usr/bin/" + argsToUse[0], argsToUse)  # (path,args)
#else:
#   os.execv(argsToUse[0], argsToUse)  # (path,args)


# Tried RunCmd & that isn't working either - it's resulting in salloc controlling terminal errors.
#from Shell import RunCmd
#def run(cmd):
#    print 'running %s'%cmd
#    print 'Set echoOutput to false to avoid seeing the queue contents repeatedly'
#    return RunCmd(cmd, echoOutput=0, echoCmd=True)[1]

