# -*-makefile-*-
# Spheral++ Python package makefile
#-------------------------------------------------------------------------------
PKGNAME = Python
PKGDIR = $(PKGNAME)/
SRCTARGETS =
PYFFLETARGETS =
PYTHONTARGETS = \
	Spheral.py \
	Spheral1d.py \
	Spheral2d.py \
	Spheral3d.py \
	SpheralPickle.py \
	SpheralTestUtilities.py \
	SpheralTimer.py \
	SpheralGnuPlotUtilities.py \
	SpheralMatplotlibUtilities.py \
	SpheralMayaViUtilities.py \
	loadmpi.py \
	Pnorm.py \
	SpheralConservation.py \
	SpheralController.py \
	SpheralOptionParser.py \
	PlotKernel2d.py \
	fakempi.py \
	SpheralVisitDump.py \
	findLastRestart.py \
	newtonRaphson.py

LINKLIST = linklist
PYFFLELIST = pyfflelist
SPHERALTOP = ../..
ARCH = $(SPHERALARCH)

#-------------------------------------------------------------------------------
include $(SPHERALTOP)/helpers/makefile_taumaster
include $(SPHERALTOP)/helpers/makefile_master
